import { useState, useEffect } from 'react'
import JobDescriptionInput from './components/JobDescriptionInput'
import TechStackResults from './components/TechStackResults'
import LearningRoadmap from './components/LearningRoadmap'
import Header from './components/Header'
import AIProviderConfig from './components/AIProviderConfig'
import { analyzeTechStack, type AIConfig } from './services/aiService'
import { Loader2, Download } from 'lucide-react'

export interface TechStack {
  technologies: Array<{
    name: string;
    category: string;
    importance: 'required' | 'preferred' | 'nice-to-have';
    description: string;
  }>;
  roadmap: Array<{
    phase: string;
    duration: string;
    topics: string[];
    resources: string[];
  }>;
  summary: string;
}

const STORAGE_KEY = 'techstack_ai_config'

function App() {
  const [jobDescription, setJobDescription] = useState('')
  const [isAnalyzing, setIsAnalyzing] = useState(false)
  const [results, setResults] = useState<TechStack | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [aiConfig, setAiConfig] = useState<AIConfig>({
    provider: 'openai',
    apiKey: '',
    model: 'gpt-5',
  })

  // Load config from localStorage on mount
  useEffect(() => {
    const stored = localStorage.getItem(STORAGE_KEY)
    if (stored) {
      try {
        const config = JSON.parse(stored) as AIConfig
        setAiConfig(config)
      } catch (e) {
        console.error('Failed to load config:', e)
      }
    }
  }, [])

  // Save config to localStorage whenever it changes
  const handleConfigChange = (config: AIConfig) => {
    setAiConfig(config)
    localStorage.setItem(STORAGE_KEY, JSON.stringify(config))
  }

  const handleAnalyze = async () => {
    if (!jobDescription.trim()) {
      setError('Please enter a job description')
      return
    }

    if (!aiConfig.apiKey) {
      setError('Please enter your API key above')
      return
    }

    setIsAnalyzing(true)
    setError(null)
    setResults(null)

    try {
      const analysis = await analyzeTechStack(aiConfig, jobDescription)
      setResults(analysis)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to analyze job description')
    } finally {
      setIsAnalyzing(false)
    }
  }

  const handleReset = () => {
    setJobDescription('')
    setResults(null)
    setError(null)
  }

  const handleDownload = () => {
    if (!results) return

    // Create markdown content
    let markdown = `# Tech Stack Analysis & Learning Roadmap\n\n`
    markdown += `**Generated on:** ${new Date().toLocaleDateString()}\n\n`
    markdown += `---\n\n`
    
    // Summary
    markdown += `## Summary\n\n${results.summary}\n\n---\n\n`
    
    // Tech Stack
    markdown += `## Tech Stack Breakdown\n\n`
    const groupedTechs = results.technologies.reduce((acc, tech) => {
      if (!acc[tech.category]) acc[tech.category] = []
      acc[tech.category].push(tech)
      return acc
    }, {} as Record<string, typeof results.technologies>)
    
    Object.entries(groupedTechs).forEach(([category, techs]) => {
      markdown += `### ${category}\n\n`
      techs.forEach(tech => {
        const badge = tech.importance === 'required' ? '🔴' : tech.importance === 'preferred' ? '🟡' : '🟢'
        markdown += `- ${badge} **${tech.name}** (${tech.importance})\n`
        markdown += `  - ${tech.description}\n\n`
      })
    })
    
    markdown += `---\n\n`
    
    // Learning Roadmap
    markdown += `## Learning Roadmap\n\n`
    results.roadmap.forEach((phase, index) => {
      markdown += `### Phase ${index + 1}: ${phase.phase}\n\n`
      markdown += `**Duration:** ${phase.duration}\n\n`
      markdown += `**Topics to Learn:**\n`
      phase.topics.forEach(topic => {
        markdown += `- ${topic}\n`
      })
      markdown += `\n**Recommended Resources:**\n`
      phase.resources.forEach(resource => {
        markdown += `- ${resource}\n`
      })
      markdown += `\n---\n\n`
    })
    
    markdown += `\n_Generated by Tech Stack Analyzer_`
    
    // Create and download file
    const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `tech-stack-roadmap-${Date.now()}.md`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100">
      <Header />
      
      <main className="container mx-auto px-4 py-8 max-w-6xl">
        {!results ? (
          <div className="max-w-4xl mx-auto space-y-6">
            <AIProviderConfig
              config={aiConfig}
              onChange={handleConfigChange}
            />
            
            <JobDescriptionInput
              value={jobDescription}
              onChange={setJobDescription}
              onAnalyze={handleAnalyze}
              isAnalyzing={isAnalyzing}
            />
            
            {error && (
              <div className="mt-4 p-4 bg-red-50 border border-red-200 rounded-lg text-red-700">
                {error}
              </div>
            )}
            
            {isAnalyzing && (
              <div className="mt-8 flex flex-col items-center justify-center">
                <Loader2 className="w-12 h-12 animate-spin text-primary-600 mb-4" />
                <p className="text-gray-600 text-lg">Analyzing job description...</p>
                <p className="text-gray-500 text-sm mt-2">This may take a few moments</p>
              </div>
            )}
          </div>
        ) : (
          <div className="space-y-8">
            <div className="flex justify-between items-center">
              <h2 className="text-2xl font-bold text-gray-800">Analysis Results</h2>
              <div className="flex space-x-3">
                <button
                  onClick={handleDownload}
                  className="btn-primary flex items-center space-x-2"
                >
                  <Download className="w-5 h-5" />
                  <span>Download Roadmap</span>
                </button>
                <button
                  onClick={handleReset}
                  className="btn-secondary"
                >
                  Analyze Another
                </button>
              </div>
            </div>
            
            <div className="card">
              <h3 className="text-xl font-semibold text-gray-800 mb-4">Summary</h3>
              <p className="text-gray-700 leading-relaxed">{results.summary}</p>
            </div>

            <TechStackResults technologies={results.technologies} />
            <LearningRoadmap roadmap={results.roadmap} />
          </div>
        )}
      </main>

      <footer className="bg-white border-t border-gray-200 mt-16 py-8">
        <div className="container mx-auto px-4 text-center text-gray-600">
          <p>© 2025 <a href="https://www.ainternals.com" target="_blank" rel="noopener noreferrer" className="text-primary-600 hover:text-primary-700 font-medium">ainternals.com</a> - Tech Stack Analyzer. Powered by AI.</p>
        </div>
      </footer>
    </div>
  )
}

export default App
